-- preload.sql — generated by preload.py at 2026-05-05T23:23:02Z
-- Restores TABPFN_DB after DROP DATABASE or DROP TABLE META_DATASET_INDEX.
--
-- NOTE: Compute pools (DEEPSET_GPU_POOL, DEEPSET_CPU_POOL, AUTOGLUON_CPU_POOL),
-- network rules, and external access integrations are account-level objects
-- that survive a database drop. Recreate them from sql/run_training_job.sql
-- Steps 2 and 2b ONLY if they were explicitly dropped.
--
-- Run with: snowsql -c <connection> -f preload.sql
--


!set exit_on_error=true
!set variable_substitution=false


-- ------------------------------------------------------------------
-- Section 1 — Context
-- ------------------------------------------------------------------
USE DATABASE TABPFN_DB;
USE SCHEMA TABPFN_SCHEMA;
USE WAREHOUSE COMPUTE_WH;


-- ------------------------------------------------------------------
-- Section 2 — Stages (idempotent)
-- ------------------------------------------------------------------
CREATE STAGE IF NOT EXISTS META_DATASET_STAGE  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS MODEL_STAGE  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS EVALUATION_RESULTS_STAGE  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS MLJOB_PAYLOAD_STAGE  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS EPOCH_STAGE  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');


-- ------------------------------------------------------------------
-- Section 3 — META_DATASET_INDEX table
-- ------------------------------------------------------------------
DROP TABLE IF EXISTS META_DATASET_INDEX;
CREATE TRANSIENT TABLE META_DATASET_INDEX (
  split        STRING NOT NULL,
  task_id      STRING NOT NULL,
  stage_path   STRING NOT NULL,
  n            NUMBER,
  p            NUMBER,
  n_train      NUMBER,
  n_test       NUMBER,
  prior_regime STRING,
  hpo_bucket   NUMBER
)
DATA_RETENTION_TIME_IN_DAYS = 0
CLUSTER BY (split, hpo_bucket, prior_regime, p, n_train);


-- ------------------------------------------------------------------
-- Section 4 — Clean @MODEL_STAGE/scripts/
-- ------------------------------------------------------------------
REMOVE @MODEL_STAGE/scripts/ PATTERN='.*[.]py';


-- ------------------------------------------------------------------
-- Section 5 — Upload Python scripts
-- ------------------------------------------------------------------
PUT file://C:/Documents/TabPFN_DemandModel/src/*.py
    @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://C:/Documents/TabPFN_DemandModel/scripts/*.py
    @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;


-- ------------------------------------------------------------------
-- Section 6 — Upload synthetic datasets
-- ------------------------------------------------------------------
REMOVE @META_DATASET_STAGE/train/;
REMOVE @META_DATASET_STAGE/val/;
REMOVE @META_DATASET_STAGE/test/;
PUT file://C:/Documents/TabPFN_DemandModel/data/train/*.parquet
    @META_DATASET_STAGE/train/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://C:/Documents/TabPFN_DemandModel/data/val/*.parquet
    @META_DATASET_STAGE/val/   AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://C:/Documents/TabPFN_DemandModel/data/test/*.parquet
    @META_DATASET_STAGE/test/  AUTO_COMPRESS=FALSE OVERWRITE=TRUE;


-- ------------------------------------------------------------------
-- Section 7 — Kaggle benchmark datasets
-- ------------------------------------------------------------------
-- No .npz files found in data/kaggle/ on this machine.
-- To upload Kaggle benchmark datasets, either:
--   a) Copy .npz files to data/kaggle/ and re-run preload.py, OR
--   b) After running this script, call:
--        CALL download_kaggle_to_stage();
--        LIST @META_DATASET_STAGE/kaggle/;
--
-- REMOVE @META_DATASET_STAGE/kaggle/;
-- PUT file://C:/Documents/TabPFN_DemandModel/data/kaggle/*.npz
--     @META_DATASET_STAGE/kaggle/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;


-- ------------------------------------------------------------------
-- Section 8 — Stored procedures
-- ------------------------------------------------------------------
-- download_kaggle_to_stage() is a setup job that fetches Kaggle competition
-- data and uploads it to @META_DATASET_STAGE/kaggle/. Run after scripts are
-- staged and before the first benchmark that needs Kaggle data.
CREATE OR REPLACE PROCEDURE download_kaggle_to_stage()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_training_job.py')
  HANDLER = 'run_training_job.run_kaggle_download';

-- build_meta_dataset_index() lists @META_DATASET_STAGE/{train,val,test}/,
-- reads scalar parquet metadata, truncates/rebuilds META_DATASET_INDEX,
-- and validates 800/100/100 split counts.
CREATE OR REPLACE PROCEDURE build_meta_dataset_index()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_training_job.py')
  HANDLER = 'run_training_job.build_meta_dataset_index';

-- run_pretrain_pipeline() trains with default hyperparameters and writes
-- @MODEL_STAGE/checkpoints/pretrain.pt. Run before run_hpo_pipeline() so
-- HPO trials warm-start from the pre-trained weights.
CREATE OR REPLACE PROCEDURE run_pretrain_pipeline()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_pretrain_job.py')
  HANDLER = 'run_pretrain_job.run_pretrain_pipeline';

-- run_hpo_pipeline() launches hpo.py on the GPU pool using Ray Tune.
-- Produces @MODEL_STAGE/hpo/best_config.json on success.
CREATE OR REPLACE PROCEDURE run_hpo_pipeline()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_hpo_job.py')
  HANDLER = 'run_hpo_job.run_hpo_pipeline';

-- run_model_training() reads @MODEL_STAGE/hpo/best_config.json and produces
-- @MODEL_STAGE/checkpoints/best.pt.
CREATE OR REPLACE PROCEDURE run_model_training()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_model_training_job.py')
  HANDLER = 'run_model_training_job.run_model_training';

-- run_training_pipeline() runs the full 3-phase pipeline in sequence:
--   Phase 1 (Pretrain)       -> @MODEL_STAGE/checkpoints/pretrain.pt
--   Phase 2 (HPO fine-tune)  -> @MODEL_STAGE/hpo/best_config.json
--   Phase 3 (Final training) -> @MODEL_STAGE/checkpoints/best.pt
CREATE OR REPLACE PROCEDURE run_training_pipeline()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_training_job.py')
  HANDLER = 'run_training_job.run_pipeline';

-- run_hpo_epoch_test() runs baseline and marginal HPO epoch timing sweeps.
-- Result at @EPOCH_STAGE/hpo_timing.json.
CREATE OR REPLACE PROCEDURE run_hpo_epoch_test()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_epoch_tests.py')
  HANDLER = 'run_epoch_tests.run_hpo_epoch_test';

-- run_train_epoch_test() runs one DDP training epoch with the production
-- GPU_NV_M topology: 10 nodes x 4 workers/node = world_size 40.
-- Result at @EPOCH_STAGE/train_timing.json.
CREATE OR REPLACE PROCEDURE run_train_epoch_test()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_epoch_tests.py')
  HANDLER = 'run_epoch_tests.run_train_epoch_test';

-- prepare_benchmark_datasets() fetches OpenML/Kaggle benchmark datasets once,
-- stages them to @META_DATASET_STAGE/benchmark_prepared/, and writes
-- benchmark_manifest.json. Run before run_evaluation_pipeline(), or let
-- run_evaluation_pipeline() call it automatically.
-- @META_DATASET_STAGE/benchmark_prepared/ is created by this procedure.
-- It contains benchmark_manifest.json and prepared .npz files for all benchmark datasets.
-- Benchmark shard jobs read from this prefix; they do not call OpenML directly.
-- To rebuild: set BENCHMARK_FORCE_REBUILD=true env var before calling this procedure.
CREATE OR REPLACE PROCEDURE prepare_benchmark_datasets()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  ARTIFACT_REPOSITORY = snowflake.snowpark.pypi_shared_repository
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python', 'openml==0.15.1')
  EXTERNAL_ACCESS_INTEGRATIONS = (BENCHMARK_EXTERNAL_ACCESS)
  IMPORTS = ('@MODEL_STAGE/scripts/prepare_benchmark_datasets.py')
  HANDLER = 'prepare_benchmark_datasets.prepare_datasets';

-- run_evaluation_pipeline() requires @MODEL_STAGE/checkpoints/best.pt,
-- then runs (concurrently) synthetic eval and benchmark dataset preparation,
-- then all benchmark shard jobs, then the aggregate comparison job.
CREATE OR REPLACE PROCEDURE run_evaluation_pipeline(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_evaluation_pipeline';

-- Drop old zero-argument overload if it exists:
DROP PROCEDURE IF EXISTS run_evaluation_pipeline();

-- Call:
-- CALL run_evaluation_pipeline('<prep_runtime>', '2.5.0-py311', '<autogluon_runtime>');

-- run_evaluation_runtime_probes() runs all preflight checks without submitting
-- evaluation jobs. Use this to validate runtime environments before a full run.
CREATE OR REPLACE PROCEDURE run_evaluation_runtime_probes(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_evaluation_runtime_probes';

-- Call:
-- CALL run_evaluation_runtime_probes('<prep_runtime>', '2.5.0-py311', '<autogluon_runtime>');

-- run_evaluation_capacity_probe() is a lightweight quota/capacity check. It submits
-- capacity_probe.py in 3 non-overlapping phases matching the fixed evaluation pipeline
-- envelope (GPU=10, CPU=3, AutoGluon=5). Run between runtime probes and the full pipeline.
CREATE OR REPLACE PROCEDURE run_evaluation_capacity_probe(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_evaluation_capacity_probe';

-- Call:
-- CALL run_evaluation_capacity_probe('<prep_runtime>', '2.5.0-py311', '<autogluon_runtime>');

-- Split-phase evaluation: run each phase independently to release quota between pools.
-- run_evaluation_prep() fetches/validates benchmark manifest and index on DEEPSET_CPU_POOL.
CREATE OR REPLACE PROCEDURE run_evaluation_prep(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_evaluation_prep';

-- run_deepset_evaluation() runs synthetic eval and 10 DeepSet GPU shards on DEEPSET_GPU_POOL.
-- Requires @MODEL_STAGE/checkpoints/best.pt.
CREATE OR REPLACE PROCEDURE run_deepset_evaluation(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_deepset_evaluation';

-- run_baseline_evaluation() runs 3 CPU baseline benchmark shards on DEEPSET_CPU_POOL.
CREATE OR REPLACE PROCEDURE run_baseline_evaluation(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_baseline_evaluation';

-- run_autogluon_evaluation() runs 30 AutoGluon shards (max 5 concurrent) on AUTOGLUON_CPU_POOL.
CREATE OR REPLACE PROCEDURE run_autogluon_evaluation(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_autogluon_evaluation';

-- run_evaluation_aggregation() runs the benchmark aggregation job on DEEPSET_CPU_POOL
-- and returns a listing of @EVALUATION_RESULTS_STAGE. Can be re-run without re-running
-- prior phases if benchmark_parts/ files already exist on stage.
CREATE OR REPLACE PROCEDURE run_evaluation_aggregation(
  PREP_RUNTIME_ENVIRONMENT STRING,
  BENCHMARK_RUNTIME_ENVIRONMENT STRING,
  AUTOGLUON_RUNTIME_ENVIRONMENT STRING
)
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  PACKAGES = ('snowflake-snowpark-python', 'snowflake-ml-python')
  IMPORTS = ('@MODEL_STAGE/scripts/run_evaluation_test.py')
  HANDLER = 'run_evaluation_test.run_evaluation_aggregation';


-- ------------------------------------------------------------------
-- Section 9 — Rebuild META_DATASET_INDEX
-- ------------------------------------------------------------------
-- Requires staged parquet (Section 6) to already be uploaded.
CALL build_meta_dataset_index();


-- ------------------------------------------------------------------
-- Section 10 — Verification
-- ------------------------------------------------------------------
LIST @MODEL_STAGE/scripts/ PATTERN='.*[.]py';
LIST @META_DATASET_STAGE/train/ PATTERN='.*[.]parquet';
LIST @META_DATASET_STAGE/val/   PATTERN='.*[.]parquet';
LIST @META_DATASET_STAGE/test/  PATTERN='.*[.]parquet';
SELECT split, COUNT(*) AS task_count
FROM META_DATASET_INDEX
GROUP BY split
ORDER BY split;
-- Expected: train=800, val=100, test=100
