-- run_training_job.sql
-- One-time environment setup + compute pool creation for the DeepSet training and evaluation pipelines.
-- Run steps 0-2, 2b, 3a, and 4 in Snowsight or SnowSQL.
-- Steps 3 and 3b (PUT) must be run in SnowSQL; PUT is not supported in Snowsight.
-- Training uses the Snowflake Container Runtime for ML.
-- For SnowSQL/connectors, YOUR_ACCOUNT_NAME means the Snowflake account identifier
-- from <account_identifier>.snowflakecomputing.com, preferably organization-account_name.

-- Step 0: Create database and schema
CREATE DATABASE IF NOT EXISTS TABPFN_DB;
USE DATABASE TABPFN_DB;
CREATE SCHEMA IF NOT EXISTS TABPFN_SCHEMA;
USE SCHEMA TABPFN_SCHEMA;

-- Step 1: Create stages
-- Dedicated database and schema own project stages, compute pools, and model registry entries.
-- META_DATASET_STAGE: train/val/test synthetic parquet and staged benchmark datasets.
-- MLJobs materialize this stage into ephemeral container-local /tmp/data.
CREATE STAGE IF NOT EXISTS META_DATASET_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- MODEL_STAGE: scripts, HPO config, and model checkpoints only.
CREATE STAGE IF NOT EXISTS MODEL_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- EVALUATION_DATASET_STAGE: staged synthetic regression and OOD evaluation
-- input datasets only. Production training parquet stays in META_DATASET_STAGE.
CREATE STAGE IF NOT EXISTS EVALUATION_DATASET_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- EVALUATION_RESULTS_STAGE: all synthetic reports, benchmark part CSVs, and
-- the canonical final comparison file model_comparison.csv.
CREATE STAGE IF NOT EXISTS EVALUATION_RESULTS_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- MLJOB_PAYLOAD_STAGE: bare stage name passed to submit_from_stage(stage_name=...).
-- It is separate from @MODEL_STAGE/scripts/, which is passed as source.
CREATE STAGE IF NOT EXISTS MLJOB_PAYLOAD_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- EPOCH_STAGE: output-only stage for epoch calibration JSON.
-- hpo_timing.json contains baseline, marginal sweep runs, and HPO wall-clock
-- estimates; train_timing.json contains production-topology epoch timing.
-- Runnable code is loaded from @MODEL_STAGE/scripts/.
CREATE STAGE IF NOT EXISTS EPOCH_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- META_NONLINEAR_DATASET_STAGE: train/val/test nonlinear synthetic parquet
-- (generated by generate_nonlinear_dgp.py; 800/100/100 split).
-- Separate from META_DATASET_STAGE to allow independent PUT/index rebuilds.
CREATE STAGE IF NOT EXISTS META_NONLINEAR_DATASET_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Step 2: Create compute pools
-- GPU_NV_M: 4 A10G GPUs per node. MAX_NODES=10 supports 5-node HPO
-- (20 concurrent one-GPU trials, 1 round of 20 trials) and 10-node DDP training
-- (40 DDP workers via num_workers_per_node=4).
-- CPU_X64_M: MAX_NODES=6 supports the six combined CPU baseline shard jobs.
-- Each shard owns a deterministic dataset subset and evaluates all configured
-- baseline methods across all configured seeds. Oversized CPU rows emit NaN
-- skip rows instead of exhausting container memory.
-- AUTOGLUON_CPU_POOL uses CPU_X64_M for AutoGluon shard jobs. MAX_NODES=60
-- supports legacy single-wave AutoGluon (60 single-node shards). The combined
-- suite default uses only 24 of those nodes: 6 logical AutoGluon work-item
-- clusters with 4 target instances per cluster.
-- Each combined cluster runs autogluon_ray.py
-- with Ray for distributed independent work items.
-- Single-wave execution is enforced. Lower concurrency arguments are rejected;
-- they are not used as multi-wave throttles. For combined AutoGluon, reduce
-- SYNREG_AUTOGLUON_CLUSTER_SHARDS explicitly if fewer output shard files are
-- desired, or request quota for cluster_shards * workers_per_shard nodes.
-- Run run_synthetic_regression_combined_autogluon_capacity_probe before evaluation.
-- Run run_synthetic_regression_combined_autogluon_worker_access_probe after the
-- capacity probe to validate driver-to-worker item metadata transfer and worker
-- dataset access before full AutoGluon evaluation.
-- SPCS does not support ALTER COMPUTE POOL to change INSTANCE_FAMILY; drop and recreate.
DROP COMPUTE POOL IF EXISTS DEEPSET_GPU_POOL;
CREATE COMPUTE POOL DEEPSET_GPU_POOL
  MIN_NODES = 1
  MAX_NODES = 10
  INSTANCE_FAMILY = GPU_NV_M
  AUTO_SUSPEND_SECS = 300
  INITIALLY_SUSPENDED = TRUE;

DROP COMPUTE POOL IF EXISTS DEEPSET_CPU_POOL;
CREATE COMPUTE POOL DEEPSET_CPU_POOL
  MIN_NODES = 1
  MAX_NODES = 6
  INSTANCE_FAMILY = CPU_X64_M
  AUTO_SUSPEND_SECS = 300
  INITIALLY_SUSPENDED = TRUE;

DROP COMPUTE POOL IF EXISTS AUTOGLUON_CPU_POOL;
CREATE COMPUTE POOL AUTOGLUON_CPU_POOL
  MIN_NODES = 1
  MAX_NODES = 60
  INSTANCE_FAMILY = CPU_X64_M
  AUTO_SUSPEND_SECS = 300
  INITIALLY_SUSPENDED = TRUE;

-- Verify pools reach ACTIVE before submitting the job:
SHOW COMPUTE POOLS LIKE 'DEEPSET_GPU_POOL';
SHOW COMPUTE POOLS LIKE 'DEEPSET_CPU_POOL';
SHOW COMPUTE POOLS LIKE 'AUTOGLUON_CPU_POOL';

-- Step 2b: Allow benchmark jobs to fetch datasets from inside Snowflake
-- Run with a role that can create network rules in TABPFN_SCHEMA.
-- OpenML hosts are required for evaluation. Kaggle API/www and Google storage hosts are
-- required for the one-off Kaggle download job. Benchmark shard jobs consume only
-- prepared .npz files; only the prep MLJob may use this network route and its
-- OpenML pip dependency.
USE ROLE SYSADMIN;
USE DATABASE TABPFN_DB;
USE SCHEMA TABPFN_SCHEMA;

CREATE OR REPLACE NETWORK RULE openml_network_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
    'www.openml.org',
    'openml.org',
    'api.openml.org',
    'pypi.org',
    'files.pythonhosted.org'
  );

-- If CALL download_kaggle_to_stage() fails with host='api.kaggle.com', recreate
-- this network rule and the benchmark_external_access integration below.

CREATE OR REPLACE NETWORK RULE kaggle_network_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
    'api.kaggle.com',
    'www.kaggle.com',
    'kaggle.com',
    'storage.googleapis.com',
    'pypi.org',
    'files.pythonhosted.org'
  );

-- Kaggle API authentication requires the Kaggle account username/handle,
-- not the email address used to log in. A 401 Unauthorized from
-- DownloadDataFiles means Kaggle rejected these secret values.
-- If that happens, generate a fresh Kaggle API token and recreate this secret.
-- Keep this statement in Snowsight/SnowSQL history only; do not commit real keys.
CREATE OR REPLACE SECRET KAGGLE_API_SECRET
  TYPE = PASSWORD
  USERNAME = '<kaggle_account_username_not_email>'
  PASSWORD = '<kaggle_api_key>';

-- Run with ACCOUNTADMIN or another role granted CREATE EXTERNAL ACCESS INTEGRATION.
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION benchmark_external_access
  ALLOWED_NETWORK_RULES = (openml_network_rule, kaggle_network_rule)
  ALLOWED_AUTHENTICATION_SECRETS = (KAGGLE_API_SECRET)
  ENABLED = TRUE;

-- If a non-admin role submits the procedure or MLJobs, grant it least-privilege access:
-- GRANT READ ON SECRET KAGGLE_API_SECRET TO ROLE <job_submitter_role>;
-- GRANT USAGE ON INTEGRATION benchmark_external_access TO ROLE <job_submitter_role>;

-- =====================================================================
-- Step 2c: General PyPI External Access Integration for Snowflake-managed Container Runtime
--
--   Allows Snowflake ML Jobs to install approved third-party PyPI packages
--   (CatBoost, OpenML, AutoGluon, etc.) that are NOT preinstalled in the
--   2.5.0-py311 managed runtime image. Used for all pip_requirements jobs.
--
-- Required privilege: ACCOUNTADMIN (or role with CREATE INTEGRATION and
--   access to SNOWFLAKE.EXTERNAL_ACCESS.PYPI_RULE).
-- Run this block once. After creation, grant USAGE to the role that
--   executes stored procedures and submits ML Jobs.
-- =====================================================================

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION TABPFN_PYPI_EAI
  ALLOWED_NETWORK_RULES = (SNOWFLAKE.EXTERNAL_ACCESS.PYPI_RULE)
  ENABLED = TRUE
  COMMENT = 'Allows TabPFN ML Jobs to install approved PyPI dependencies in Snowflake-managed Container Runtime.';

GRANT USAGE ON INTEGRATION TABPFN_PYPI_EAI TO ROLE ACCOUNTADMIN;

-- Verification:
-- SHOW EXTERNAL ACCESS INTEGRATIONS LIKE 'TABPFN_PYPI_EAI';
-- DESC EXTERNAL ACCESS INTEGRATION TABPFN_PYPI_EAI;
-- SHOW GRANTS ON INTEGRATION TABPFN_PYPI_EAI;

USE DATABASE TABPFN_DB;
USE SCHEMA TABPFN_SCHEMA;

-- Step 3: Upload training and benchmark data (SnowSQL only)
-- Run the three REMOVE lines first to clear stale files before re-uploading:
-- REMOVE @META_DATASET_STAGE/train/;
-- REMOVE @META_DATASET_STAGE/val/;
-- REMOVE @META_DATASET_STAGE/test/;
-- PUT file://C:/Documents/TabPFN_DemandModel/data/train/*.parquet @META_DATASET_STAGE/train/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://C:/Documents/TabPFN_DemandModel/data/val/*.parquet   @META_DATASET_STAGE/val/   AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://C:/Documents/TabPFN_DemandModel/data/test/*.parquet  @META_DATASET_STAGE/test/  AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://C:/Documents/TabPFN_DemandModel/data/kaggle/*.npz    @META_DATASET_STAGE/kaggle/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
--
-- Verify:
-- LIST @META_DATASET_STAGE/train/;
-- LIST @META_DATASET_STAGE/val/;
-- LIST @META_DATASET_STAGE/test/;
-- LIST @META_DATASET_STAGE/kaggle/;

-- Step 3a: Create and verify the metadata pruning index for HPO
-- META_DATASET_INDEX is a table-backed pruning layer over parquet payloads in
-- @META_DATASET_STAGE. It is not a replacement for staged parquet storage.
-- HPO should query this table to choose a deterministic balanced subset, then
-- materialize only those selected stage_path payloads into the MLJob container.
-- One-time migration: DROP TABLE IF EXISTS META_DATASET_INDEX;
-- (Drops the permanent version so it can be recreated as TRANSIENT)
CREATE TRANSIENT TABLE IF NOT EXISTS META_DATASET_INDEX (
  split STRING NOT NULL,
  task_id STRING NOT NULL,
  stage_path STRING NOT NULL,
  n NUMBER,
  p NUMBER,
  n_train NUMBER,
  n_test NUMBER,
  prior_regime STRING,
  hpo_bucket NUMBER
)
DATA_RETENTION_TIME_IN_DAYS = 0
CLUSTER BY (split, hpo_bucket, prior_regime, p, n_train);

-- Step 3b: Benchmark manifest metadata index
-- BENCHMARK_DATASET_INDEX is rebuilt by prepare_benchmark_datasets() from
-- benchmark_manifest.json metadata. It supports manifest completeness checks
-- and optional BENCHMARK_SHARD_STRATEGY=balanced assignment by benchmark_weight.
-- Prepared .npz files remain opaque staged payloads. Do not split, cluster, or
-- transform them for Snowflake query performance; benchmark jobs download exact
-- stage_path files only.
-- Snowflake automatic micro-partitioning is sufficient for this small metadata
-- table. Add a clustering key only after measured query benefit on a large
-- manifest, and keep it to a few useful columns such as (source, dataset_index).
CREATE TRANSIENT TABLE IF NOT EXISTS BENCHMARK_DATASET_INDEX (
  dataset_index NUMBER NOT NULL,
  source STRING,
  task_id STRING,
  dataset_id STRING,
  name STRING,
  stage_path STRING,
  n_samples NUMBER,
  n_features NUMBER,
  estimated_bytes NUMBER,
  benchmark_weight NUMBER,
  created_at_utc TIMESTAMP_NTZ
)
DATA_RETENTION_TIME_IN_DAYS = 0;

-- Step 3c: Synthetic regression dataset index
-- SYNTHETIC_REGRESSION_DATASET_INDEX is shared across all synthetic evaluation suites,
-- differentiated by suite_id. It is rebuilt by prepare_synthetic_regression.py (in-distribution)
-- and prepare_ood_regression.py (OOD pilot and full suite). Each prep job deletes only its own
-- suite_id rows; the table is never dropped unless SYNTHETIC_REGRESSION_DROP_INDEX_TABLE=true.
-- logical_dataset_key has zero-padded format: {suite_id}:{prior_regime}:{dataset_id:04d}
-- source_suite_id: populated for combined suites (e.g. linear_all_v1) to record
--   which source suite contributed each row; NULL for primary suites.
CREATE TRANSIENT TABLE IF NOT EXISTS SYNTHETIC_REGRESSION_DATASET_INDEX (
  suite_id             STRING,
  suite_family         STRING,
  dataset_id           NUMBER,
  dataset_seed         NUMBER,
  stage_path           STRING,
  prior_name           STRING,
  prior_version        STRING,
  prior_regime         STRING,
  split_seeds          ARRAY,
  n_total              NUMBER,
  n_train_default      NUMBER,
  n_holdout_default    NUMBER,
  p_signal             NUMBER,
  p_noise              NUMBER,
  p_total              NUMBER,
  target_noise_scale   FLOAT,
  training_size_anchor BOOLEAN,
  feature_noise_level  NUMBER,
  eval_weight          FLOAT,
  payload_bytes        NUMBER,
  created_at           TIMESTAMP_NTZ,
  logical_dataset_key  STRING,
  source_suite_id      STRING
) DATA_RETENTION_TIME_IN_DAYS = 0;

-- Populate/rebuild guidance:
-- 1. Upload staged parquet to @META_DATASET_STAGE/{train,val,test}/.
-- 2. Upload scripts to @MODEL_STAGE/scripts/.
-- 3. Run CALL build_meta_dataset_index(); to rebuild from staged parquet
--    metadata inside Snowflake. Re-run it whenever synthetic parquet is
--    regenerated or restaged.

-- Expected full split counts before HPO/training:
SELECT split, COUNT(*) AS task_count
FROM META_DATASET_INDEX
GROUP BY split
ORDER BY split;

-- Copy-paste assertions for the current generated dataset:
SELECT COUNT(*) AS train_tasks FROM META_DATASET_INDEX WHERE split = 'train'; -- expected 800
SELECT COUNT(*) AS val_tasks   FROM META_DATASET_INDEX WHERE split = 'val';   -- expected 100
SELECT COUNT(*) AS test_tasks  FROM META_DATASET_INDEX WHERE split = 'test';  -- expected 100

-- Inspect clustering/pruning health after loading enough rows:
SELECT SYSTEM$CLUSTERING_INFORMATION(
  'META_DATASET_INDEX',
  '(split, hpo_bucket, prior_regime, p, n_train)'
);

-- Example deterministic HPO subset checks. These mirror the intended default:
-- 200 train tasks and 40 validation tasks, balanced by hpo_bucket and stable
-- within buckets by task_id. HPO should use equivalent table-backed selection
-- before materializing payloads from @META_DATASET_STAGE.
WITH ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY split, hpo_bucket
      ORDER BY prior_regime, p, n_train, task_id
    ) AS bucket_rank
  FROM META_DATASET_INDEX
  WHERE split IN ('train', 'val')
),
selected AS (
  SELECT *
  FROM ranked
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY split
    ORDER BY bucket_rank, hpo_bucket, prior_regime, p, n_train, task_id
  ) <= IFF(split = 'train', 200, 40)
)
SELECT split, COUNT(*) AS selected_rows
FROM selected
GROUP BY split
ORDER BY split;

-- Confirm selected payload paths are concrete staged parquet references:
WITH ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY split, hpo_bucket
      ORDER BY prior_regime, p, n_train, task_id
    ) AS bucket_rank
  FROM META_DATASET_INDEX
  WHERE split IN ('train', 'val')
),
selected AS (
  SELECT *
  FROM ranked
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY split
    ORDER BY bucket_rank, hpo_bucket, prior_regime, p, n_train, task_id
  ) <= IFF(split = 'train', 200, 40)
)
SELECT split, stage_path, n, p, n_train, n_test, prior_regime, hpo_bucket
FROM selected
ORDER BY split, hpo_bucket, task_id
LIMIT 20;

-- Step 3b: Upload Python scripts (SnowSQL only)
-- Re-run whenever any script changes:
-- PUT file://C:/Documents/TabPFN_DemandModel/src/*.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://C:/Documents/TabPFN_DemandModel/scripts/*.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- After refactor: run_epoch_tests.py is now its own handler file (was in run_training_job.py).
-- PUT file://C:/Documents/TabPFN_DemandModel/scripts/run_epoch_tests.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- After refactor: run_evaluation_test.py is the evaluation handler (was in run_training_job.py).
-- PUT file://C:/Documents/TabPFN_DemandModel/scripts/run_evaluation_test.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- New: prepare_benchmark_datasets.py is the benchmark dataset prep handler (covered by src/*.py wildcard above).
-- PUT file://C:/Documents/TabPFN_DemandModel/src/prepare_benchmark_datasets.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- Evaluation runtime preflight uses runtime_probe.py (covered by src/*.py wildcard above).
-- PUT file://C:/Documents/TabPFN_DemandModel/src/runtime_probe.py @MODEL_STAGE/scripts/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- Distributed AutoGluon uses autogluon_ray.py, ray_capacity_probe.py, and
-- autogluon_worker_access_probe.py (covered by scripts/*.py wildcard above).
--
-- Verify:
-- LIST @MODEL_STAGE/scripts/;
-- Epoch calibration jobs also run from @MODEL_STAGE/scripts/. @EPOCH_STAGE is
-- output-only for hpo_timing.json, hpo_epoch_error.json, train_timing.json, and
-- train_epoch_error.json.
-- Before epoch calibration, verify the shared modules and entrypoints:
-- LIST @MODEL_STAGE/scripts/ PATTERN='.*(hpo|hpo_epoch_test|train_epoch_test|train|model|snowflake_io)[.]py';
-- Before synthetic regression evaluation, verify the orchestration and Ray entrypoints:
-- LIST @MODEL_STAGE/scripts/ PATTERN='.*(run_synthetic_regression_evaluation|evaluate_synthetic_regression|autogluon_ray|ray_capacity_probe|autogluon_worker_access_probe)[.]py';
