CREATE IMAGE REPOSITORY IF NOT EXISTS MODEL_IMAGE_REPOSITORY;
SHOW IMAGE REPOSITORIES;

CREATE ROLE IF NOT EXISTS TABPFN_IMAGE_PUSHER;
CREATE USER IF NOT EXISTS GITHUB_ACTIONS_IMAGE_PUSHER
  TYPE = SERVICE
  LOGIN_NAME = 'GITHUB_ACTIONS_IMAGE_PUSHER'
  COMMENT = 'GitHub Actions service user for pushing SPCS AutoGluon images';

GRANT ROLE TABPFN_IMAGE_PUSHER TO USER GITHUB_ACTIONS_IMAGE_PUSHER;

ALTER USER GITHUB_ACTIONS_IMAGE_PUSHER
  SET DEFAULT_ROLE = 'TABPFN_IMAGE_PUSHER';

GRANT USAGE ON DATABASE TABPFN_DB TO ROLE TABPFN_IMAGE_PUSHER;
GRANT USAGE ON SCHEMA TABPFN_DB.TABPFN_SCHEMA TO ROLE TABPFN_IMAGE_PUSHER;
GRANT READ, WRITE ON IMAGE REPOSITORY TABPFN_DB.TABPFN_SCHEMA.MODEL_IMAGE_REPOSITORY
  TO ROLE TABPFN_IMAGE_PUSHER;

CREATE AUTHENTICATION POLICY IF NOT EXISTS TABPFN_GITHUB_ACTIONS_PAT_POLICY
  PAT_POLICY = (
    NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED
    REQUIRE_ROLE_RESTRICTION_FOR_SERVICE_USERS = TRUE
  )
  COMMENT = 'Allow role-restricted PATs for GitHub Actions image push service user';

ALTER USER GITHUB_ACTIONS_IMAGE_PUSHER
  SET AUTHENTICATION POLICY TABPFN_GITHUB_ACTIONS_PAT_POLICY;

ALTER USER GITHUB_ACTIONS_IMAGE_PUSHER
    REMOVE PROGRAMMATIC ACCESS TOKEN GITHUB_ACTIONS_DOCKER_PUSH;
    
ALTER USER GITHUB_ACTIONS_IMAGE_PUSHER
  ADD PROGRAMMATIC ACCESS TOKEN GITHUB_ACTIONS_DOCKER_PUSH
  ROLE_RESTRICTION = 'TABPFN_IMAGE_PUSHER'
  DAYS_TO_EXPIRY = 90
  COMMENT = 'GitHub Actions Docker login for Snowflake image registry';

SHOW USER PROGRAMMATIC ACCESS TOKENS FOR USER
  GITHUB_ACTIONS_IMAGE_PUSHER;